apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-sc2y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-sc2y
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-sc2y
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-sc2y
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-sc2y
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mijr-tenant/rhtap-demo-app/hacbs-test-project-sc2y@sha256:81f0e6a7ba68ee84898616bdf7e871a62e1ccfbc6902da6e0a3fffa8c417cb4d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
