apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-sc2y
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mijr-tenant/rhtap-demo-app/hacbs-test-project-sc2y@sha256:81f0e6a7ba68ee84898616bdf7e871a62e1ccfbc6902da6e0a3fffa8c417cb4d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
